django/05/django_hw_5_4/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
]

django/05/django_hw_5_4/my_fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/05/django_hw_5_4/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/05/django_hw_5_4/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:index')

django/05/django_hw_5_4/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>메인 페이지</h1>
  <a href="{% url 'articles:new' %}">[CREATE]</a>

  <ul>
    {% for article in articles %}
      <li>{{ article.pk }}번째 글</li>
      <li>제목 : {{ article.title }}</li>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

django/05/django_hw_5_4/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글 생성 페이지</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title"> <br>
    <label for="content">내용:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>

    <input type="submit" value="CREATE">
  </form>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}